# Module: educrypto.encoding
# Create src/educrypto/encoding.py in your library.

def int_to_bytes(value: int) -> bytes: ...
def bytes_to_int(data: bytes) -> int: ...
def xor_bytes(left: bytes, right: bytes) -> bytes: ...

# Module: educrypto.otp
# Create src/educrypto/otp.py in your library.

def encrypt(pad: bytes, plaintext: bytes) -> bytes: ...
def decrypt(pad: bytes, ciphertext: bytes) -> bytes: ...


# Module: educrypto.attacks.week01
# Create src/educrypto/attacks/week01.py in your library.

def solve(base_url: str) -> str: ...
