# Module: educrypto.symmetric.padding

def pkcs7_pad(message: bytes, block_size: int) -> bytes: ...
def pkcs7_unpad(padded: bytes, block_size: int) -> bytes: ...

# Module: educrypto.symmetric.ecb

def encrypt(key: bytes, plaintext: bytes) -> bytes: ...
def decrypt(key: bytes, ciphertext: bytes) -> bytes: ...

